--- 
- name: install nginx
  hosts: server
  become: yes
  tasks: 
    - name: install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Reload service httpd, in all cases
      ansible.builtin.service:
        name: nginx
        state: reloaded
    - name: Change file ownership, group and permissions
      ansible.builtin.file:
        path: D:\ansiblepracties\practies\index.html
        mode: '0644'