--- 
- name: install nginx
  hosts: server
  become: yes
  tasks: 
    - name: install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: template 
      ansible.builtin.template:
        src: index.html.j2
        dest: /var/www/html/index.html
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
   