--- 
- name: install nginx
  hosts: server
  become: yes
  tasks: 
    - name: install nginx
      apt:
        name: nginx
        update_cache: yes
        state: present
    - name: Reload service httpd, in all cases
      ansible.builtin.service:
        name: nginx
        state: reloaded
    - name: create symlink
      file:
        src: index.html
        dest: /etc/nginx/sites-available/index.html
        state: link